---
abstract: 'Subclass of Time::Piece with some useful method'
author:
  - 'Nishibayashi Takuji <takuji31@gmail.com>'
build_requires: {}
configure_requires:
  Module::Build: 0.038
dynamic_config: 1
generated_by: 'Module::Build version 0.4005, CPAN::Meta::Converter version 2.130880'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Time-Piece-Plus
provides:
  Time::Piece::Plus:
    file: lib/Time/Piece/Plus.pm
    version: 0.05
requires:
  Data::Validator: 0
  Mouse: 0
  Scalar::Util: 0
  Time::Piece: 1.20
  perl: 5.010001
resources:
  license: http://dev.perl.org/licenses/
version: 0.05
